services:
  web:
    build: .
    command: gunicorn djangoTesting.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8010:8000"
    env_file:
      - ./.env.dev